name: LANCEMENT THE CHOSE

on:
  push:
    branches: [ principal ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Recupération du code
        uses: actions/checkout@v4

      - name: Installation et Build
        run: |
          npm install
          npm run build

      - name: Déploiement Web
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          
