name: DEPLOYER LE CHOISI

on:
  push:
    branches: [ principal ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Recupération du code
        uses: actions/checkout@v4

      - name: Installation et Build
        run: |
          cd Le-choisi
          npm install
          npm run build

      - name: Déploiement Web
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Le-choisi/dist
          branch: gh-pages

          
