name: DEPLOYER THE CHOSE

on:
  push:
    branches: [ principal ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Recupération du code
        uses: actions/checkout@v4

      - name: Installation et Build
        run: |
          npm install
          npm run build

      - name: Déploiement Web (Aperçu Live)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # C'est là que ton appli est prête
          branch: gh-pages # On crée une branche spéciale pour voir l'app
          
